#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

    #define TAILLE_CASE        50 // Taille d'une case, en pixels

    enum {NOCLICK, VIDE, ATOM, ADJACENT, REFLECT, ZERO, UN, DEUX, TROIS, QUATRE, CINQ, SIX, SEPT, HUIT, NEUF, HIT, STRAIGHT};
    enum {HAUT, BAS, GAUCHE, DROITE};
	enum{PERDU,TROUVE,SCORE, GAGNE, ENCOURS};


#endif // CONSTANTES_H_INCLUDED
